version: "3.9"

services:
  iris-api:
    build: ./back/iris_app
    container_name: iris-fastapi
    ports:
      - "8040:8000"
    volumes:
      - ./iris_app:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  apache-web:
    build: .back/apache_app
    container_name: iris-apache
    ports:
      - "8280:80"
    volumes:
      - ./apache_app:/usr/local/apache2/htdocs/
